version: '3.4'

name: tre-ju

x-environment:
  &env
    POSTGRES_USER: tre-ju
    POSTGRES_DB: tre-ju
    POSTGRES_PASSWORD: 1234

services:
    postgres:
        image: postgres:16.0
        restart: always
        environment: *env
        command: "-c shared_preload_libraries='pg_stat_statements'"
        volumes:
            - "postgres:/var/lib/postgresql/data"
        ports:
            - "11632:5432"
        networks:
            - postgres

    redis:
        image: redis
        restart: always
        ports:
            - "11379:6379"
        networks:
            - redis

volumes:
    postgres:

networks:
    postgres:
    redis:
